### PR TITLE
Hexagonal_Lattice_Graph() and Triangular_Lattice_Graph() 

### PR DESCRIPTION
**Pull request by JoeyT1994**
Adds the functions `hexagonal_lattice_graph(m::Int64, n::Int64; periodic=false)` and `triangular_lattice_graph(m::Int64, n::Int64; periodic=false)` which creates a graph corresponding to a hexagonal and equilateral triangular tiling of a plane respectively.

Corresponding tests are implemented.

See the `networkx` functions: https://networkx.org/documentation/stable/reference/generated/networkx.generators.lattice.hexagonal_lattice_graph.html and https://networkx.org/documentation/stable/_modules/networkx/generators/lattice.html#triangular_lattice_graph for the Python versions. These functions are identical to those.

Additionally the functions `rem_vertices!()` and `rem_vertices()` have been added which remove lists of vertices from a `namedgraph`.

### CODE REVIEW

**Comment by mtfishman** [comment]
Great, thanks! Could you add a short test? Something like constructing a small graph and checking it has some of the correct edges, for example.

**Comment by JoeyT1994** [comment]
Sure! Just added a test. Can then expand on it as I add in new Named Graph Generators (likely to add ones we might want to simulate some Physics on - Triangular, Kagome, Unit Disk etc)

**Comment by mtfishman** [comment]
Great! This will be really useful to have, and it's nice to see how easy it is to define different lattices.

In ITensors.jl we have similar constructors which create so-called "Lattices": https://github.com/ITensor/ITensors.jl/blob/main/src/physics/lattices.jl (which are basically very simple graph types with some metadata and integer vertex labels, if we try to map it to our more modern graph parlance). I think this is a nicer design and should supersede those types (even for DMRG), since it is based on a fully fleshed out graph type and supports tuple vertices which are easier to work with for 2D lattices.@emstoudenmire probably this is of interest to you.

**Comment by emstoudenmire** [comment]
Yes, very nice to have.

The main thing needed to supersede the "lattice functions" in ITensors.jl would be that the vertex numbering of these new graph structures would map onto a good MPS path for DMRG calculations. Maybe that's a pretty natural thing to insist on, unless there's a need for another kind of ordering of the vertices?

**Comment by JoeyT1994** [comment]
@emstoudenmire that raises an interesting point because I think ideally this would ideally be dealt with by some sort of function `map_to_path(g::AbstractGraph; kwargs)` which takes an arbitrary graph and determines an optimal ordering of the vertices (probably just by analysing the adjacency matrix of `g`) for the MPS based on some `kwargs` criteria. This is discussed a bit in issue https://github.com/mtfishman/ITensorNetworks.jl/issues/19.
 I think we could employ several simple options to start with: such as bandwidth minimisation (with Cuthill Mckee or some more sophisticated cost-function) and minimising the average path length (along the MPS) between neighbours of `g`.

**Comment by mtfishman** [comment]
I agree with the above points. Just for completeness:

In order for this to replace the "Lattice" types in ITensors.jl, as Miles pointed out you would still need to define a linear ordering of the vertices which would define the MPS site ordering. But I think that is an advantage of this design, since it decouples the lattice from the MPS ordering, and therefore the same lattice definitions can be used in a variety of algorithms and contexts (such as DMRG, TTN, PEPS, etc.). It also makes it easier to try out more exotic MPS orderings such as [Hilbert curves](https://en.wikipedia.org/wiki/Hilbert_curve) (like in https://arxiv.org/abs/2105.02239).

As Miles said, we would want to define some simple default orderings for basic lattices (like the snake pattern for square and square-like lattices), and then we can have automated graph-based functions to determine orderings like Joey pointed out.

Interestingly, I think many basic orderings we use in DMRG can be "derived" by calling general graph functions, for example a depth-first search of a grid graph gives a snake pattern:
```julia
using GeometryBasics
using NamedGraphs
using ITensorNetworks
using ITensorUnicodePlots

dims = (4, 6)
g = named_grid(dims)
T = ITensorNetwork(g; link_space=2)
layout(g) = [Point(Tuple(CartesianIndices(dims)[v])) for v in  vertices(g)]  
@visualize T layout=layout edge_labels=fill("", ne(T))
t = dfs_tree(T, (1, 1))
@visualize t layout=layout edge_labels=fill("", ne(t))
```
which outputs:
```julia
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀T(1, 6)⣀⣀⣀⣀⣀⣀⣀T(2, 6)⣀⣀⣀⣀⣀⣀T(3, 6)⣀⣀⣀⣀⣀⣀⣀T(4, 6)⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀T(1, 5)⠒⠒⠒⠒⠒⠒⠒T(2, 5)⠒⠒⠒⠒⠒⠒T(3, 5)⠒⠒⠒⠒⠒⠒⠒T(4, 5)⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀T(1, 4)⣀⣀⣀⣀⣀⣀⣀T(2, 4)⣀⣀⣀⣀⣀⣀T(3, 4)⣀⣀⣀⣀⣀⣀⣀T(4, 4)⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀T(1, 3)⠒⠒⠒⠒⠒⠒⠒T(2, 3)⠒⠒⠒⠒⠒⠒T(3, 3)⠒⠒⠒⠒⠒⠒⠒T(4, 3)⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀T(1, 2)⣀⣀⣀⣀⣀⣀⣀T(2, 2)⣀⣀⣀⣀⣀⣀T(3, 2)⣀⣀⣀⣀⣀⣀⣀T(4, 2)⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀T(1, 1)⠒⠒⠒⠒⠒⠒⠒T(2, 1)⠒⠒⠒⠒⠒⠒T(3, 1)⠒⠒⠒⠒⠒⠒⠒T(4, 1)⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀t(1, 6)⣀⣀⣀⣀⣀⣀⣀t(2, 6)⣀⣀⣀⣀⣀⣀t(3, 6)⣀⣀⣀⣀⣀⣀⣀t(4, 6)⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀t(1, 5)⠒⠒⠒⠒⠒⠒⠒t(2, 5)⠒⠒⠒⠒⠒⠒t(3, 5)⠒⠒⠒⠒⠒⠒⠒t(4, 5)⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀t(1, 4)⣀⣀⣀⣀⣀⣀⣀t(2, 4)⣀⣀⣀⣀⣀⣀t(3, 4)⣀⣀⣀⣀⣀⣀⣀t(4, 4)⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀t(1, 3)⠒⠒⠒⠒⠒⠒⠒t(2, 3)⠒⠒⠒⠒⠒⠒t(3, 3)⠒⠒⠒⠒⠒⠒⠒t(4, 3)⠀⠀ 
    ⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀t(1, 2)⣀⣀⣀⣀⣀⣀⣀t(2, 2)⣀⣀⣀⣀⣀⣀t(3, 2)⣀⣀⣀⣀⣀⣀⣀t(4, 2)⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀t(1, 1)⠒⠒⠒⠒⠒⠒⠒t(2, 1)⠒⠒⠒⠒⠒⠒t(3, 1)⠒⠒⠒⠒⠒⠒⠒t(4, 1)⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 

```
So there may be simple heuristic algorithms like that we can use that automatically determine standard linear orderings for basic lattices, which then may generalize reasonably well to other lattices.

**Pull request merged**
